- .gitignore
- index.js
- package.json
> Setting up  nodejs

- .gitignore
- package.json
> Corrected gitignore and package.json

- package.json
> Correcting auth-route

- app.js
- data/migrations/20200220215820_initial.js
- data/migrations/20200225221354_members_unique_update.js
- data/seeds/01-households.js
- data/seeds/02-members.js
- data/seeds/03-todos.js
- data/seeds/04-rewards.js
- data/seeds/05-inventory.js
- data/seeds/06-bills.js
- data/seeds/101-household_members.js
- data/seeds/102-todos_members.js
- package.json
Adds the unique constraint to both username and email columns on the members table. Also removes the id field from the members seed so that the postgres internal counter stays in-sync.
- Tested on staging with postman.
> Adding unique constraints to members and resolving postgres probs with seed file

- routes/auth-router.js
> OAuth Final

- routes/auth-router.js
> Corrected frontend route

- middleware/emailTemplates.js
Updated the links sent in confirm/pw reset emails to match front end routes and added a new envvar FE_URL as part of this change.
> changed email endpoint links according to updated react app

- data/migrations/20200218211829_home-run-data.js
- data/seeds/02-members.js
- data/seeds/07-children.js
- data/seeds/102-todos_members.js
- models/members-model.js
- routes/members-router.js
- routes/todos-router.js
> Members table

- data/seeds/03-todos.js
- models/todos-model.js
- routes/auth-router.js
- routes/todos-router.js
Routes for crudding and assigning todos
> Todo routes

- __tests__/members-model.test.js
- data/dbConfig.js
- knexfile.js
- package.json
> Setup basic test folder

- package.json
> Setup test environment

- README.md
> half way through read me doc

- routes/members-router.js
> Fixing Heroku issue

- app.js
- data/dbConfig.js
- data/seeds/02-members.js
- middleware/emailTemplates.js
- middleware/restricted.js
- middleware/token.js
- models/members-model.js
- routes/auth-router.js
- routes/members-router.js
Endpoints to send a household invite email and update a users current household after following that link.
> Household invites

- routes/members-router.js
- routes/todos-router.js
> pulling householdid off token instead of req.params

- models/todos-children-model.js
- models/todos-members-model.js
- routes/todos-router.js
No longer accepting multiple assignees at once, just doing them one at a time to match the front-end.
> changed assign/unassign to work with one user at a time

- models/households-model.js
- routes/auth-router.js
- routes/households-router.js
Creates a new household with a random hexadecimal id and assigns the member's current_household to that id.
- Manually tested locally with postman for both email and oauth signups
> Create household on signup

- models/todos-model.js
- routes/todos-router.js
Updated the PUT route for todos to include the assigned users in the return value so that we can update state on the front end accordingly.
Changed the route to retrieve all todos assigned to one member. Route is now: baseURL/todos/member and pulls the user ID off the token.
Added route to retrieve all todos assigned to one child. Route is: baseURL/todos/member and pulls the user ID off the token.
** Do we need to figure out how to handle the child's ID? Do we get a token when switching to a child account? Do we store the child id in state?
> Return assignees

- routes/todos-router.js
> reverted old change to delete route

- __tests__/members-model.test.js
- data/migrations/20200415191246_default-status-update.js
> Codeclimate fixes

- routes/todos-router.js
Adjusting for code-smells on code-climate.
> Adjusting for 'code smells' in todos-router.js

- middleware/userMethodFilter.js
- routes/todos-router.js
Abstracted to middleware. Testing with this PR to master.
> Abstracted functionality to Middleware.

- middleware/userMethodFilter.js
- routes/todos-router.js
> Codeclimate fix

- db/migrations/20200416220947_create-categories.js
- db/seeds/105-todo_categories.js
- models/categories-model.js
- routes/categories-router.js
- routes/todos-router.js
> Categorization

- db/seeds/02-members.js
- db/seeds/03-todos.js
- db/seeds/07-children.js
- db/seeds/102-todos_members.js
- db/seeds/103-todos_children.js
- db/seeds/105-todo_categories.js
- package.json
Added some more realistic data to the seeds.
> added more realistic data to the seeds

- __tests__/categories-router.test.js
- package.json
- routes/auth-router.js
adds some tests for the categories-router
updated the package.json and installed the cross-env dependency - test should work now without manually having to put in 'testing' for the environment. Also knexfile uses a separate db for testing so if you dont have a separate testing database make sure to update your knexfile accordingly
> Categories router testing

- __tests__/todos-router.test.js
- __tests__/token.test.js
- routes/todos-router.js
adds test for the todo router
- Checks that the route fails when no token present on the header
-  Checks that the route succeeds when token is present
- Checks that when the route succeeds it returns the right things
> Todos router tests

- .codeclimate.yml
- [x ] Bug fix (non-breaking change which fixes an issue)
> Removing hyphen for fix attempt c12 Codeclimate error.

- .codeclimate.yml
> Activating sample .codeclimate.yml data

- .codeclimate.yml
> Cleaning up .codeclimate.yml

- .codeclimate.yml
> Removed spaces in codeclimate.yml

- .codeclimate.yml
> Removed extras in codeclimate.yml

- .codeclimate.yml
> Removed spacing in codeclimate.yml

- .codeclimate.yaml
> Removing everything except exclude patterns. Test

- .codeclimate.yaml
- __tests__/userMethodFilter.test.js
> Changing exclude patterns to single quotes

- .codeclimate.yaml
> Changing spacing in codeclimate.yaml

- .codeclimate.yml
- __tests__/app.test.js
- __tests__/userMethodFilter.test.js
> Adding test coverage for userMethodFilter and auth-router

- __tests__/auth-router.test.js
- __tests__/userMethodFilter.test.js
> Testing vh

- knexfile.js
> updated prod data for knexfile

- README.md
- knexfile.js
- package.json
Details the requirements of a local environment for running local databases and testing. Also cleans some mismatches in dependencies/devDependencies and the knexfile env variable names.
> Update README with env setup; clean up project.json and knexfile

- .github/workflows/ci.yml
- package.json
Fixes the issue where the tests failed to pass due to Postgres connection errors
Github actions summaries
> Fix actions

- __tests__/dummy.test.js
- package.json
Fixes GitHub PR status not showing whether tests fail or not, which allow failing tests to pass PR checks
GitHub actions summaries
> Remove 'failproof'

- jest.config.js
Fixes a test erroring out locally due to time constraints 
- Increasing the test's allotted time by 3x default, and running locally to confirm the tests passed.
> Add jest config to increase timeout length for local testing

- README.md
- app.js
- routes/contact-router.js
> new contact endpoint created

- middleware/emailTemplates.js
- middleware/restricted.js
- models/confirmations-model.js
- models/members-model.js
- routes/auth-router.js
- routes/members-router.js
- routes/todos-router.js
Fixes a couple security problems and gets the member invites working properly. Also changes the 'todos' response object
- Existing tests with Jest, postman, and a local view of the website depending on it
> Fix confirms

- models/members-model.js
Fixes an issue where your username would be undefined after accepting an invite
- Existing tests, and frankly it's such a simple change that it can be verified on sight
> Fix object returned from members-model update
